CREATE TABLE phonez
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number       VARCHAR(255),
    city_code    VARCHAR(255),
    country_code VARCHAR(255),
    id_user      VARCHAR(255),
    CONSTRAINT pk_phonez PRIMARY KEY (id)
);

CREATE TABLE userz
(
    id         VARCHAR(255) NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    created    TIMESTAMP,
    last_login TIMESTAMP,
    modified   TIMESTAMP,
    is_active  BOOLEAN      NOT NULL,
    token      VARCHAR(255),
    CONSTRAINT pk_userz PRIMARY KEY (id)
);

ALTER TABLE phonez
    ADD CONSTRAINT FK_PHONEZ_ON_ID_USER FOREIGN KEY (id_user) REFERENCES userz (id);